spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://82.223.202.137:3306/COMPANY
    username: curso
    password: Cursocurso1;
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    rest:
      base-path: /api
   