spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
<<<<<<< HEAD
    url: jdbc:mysql://82.223.202.137:3306/COMPANY
=======
    url: jdbc:mysql://82.223.202.137:3306/BANCO
>>>>>>> 184b25c0d034011f4f3dabb3ba52d0c463d84587
    username: curso
    password: Cursocurso1;
    
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      use-new-id-generator-mappings: false
<<<<<<< HEAD
  data:
    rest:
      base-path: /api
   
=======
  
   
>>>>>>> 184b25c0d034011f4f3dabb3ba52d0c463d84587
